# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-21 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bndryfile', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
