# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runtide', '0003_obsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='obsfile',
            name='noiters',
            field=models.IntegerField(default=5),
        ),
    ]
