# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-03 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meshbinupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meshbin', models.FileField(upload_to=b'documents/')),
                ('meshbinid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrainviewer.Adminupload')),
            ],
        ),
        migrations.CreateModel(
            name='Renderoneupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renderone', models.FileField(upload_to=b'documents/')),
                ('renderoneid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrainviewer.Adminupload')),
            ],
        ),
        migrations.CreateModel(
            name='Rendertwoupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendertwo', models.FileField(upload_to=b'documents/')),
                ('rendertwoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terrainviewer.Adminupload')),
            ],
        ),
    ]
